//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainsClient.TrainsServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PathsQuery", Namespace="http://schemas.datacontract.org/2004/07/TrainsService")]
    [System.SerializableAttribute()]
    public partial class PathsQuery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArrivalTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeavingTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetCityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArrivalTime {
            get {
                return this.ArrivalTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ArrivalTimeField, value) != true)) {
                    this.ArrivalTimeField = value;
                    this.RaisePropertyChanged("ArrivalTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeavingTime {
            get {
                return this.LeavingTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.LeavingTimeField, value) != true)) {
                    this.LeavingTimeField = value;
                    this.RaisePropertyChanged("LeavingTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceCity {
            get {
                return this.SourceCityField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceCityField, value) != true)) {
                    this.SourceCityField = value;
                    this.RaisePropertyChanged("SourceCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetCity {
            get {
                return this.TargetCityField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetCityField, value) != true)) {
                    this.TargetCityField = value;
                    this.RaisePropertyChanged("TargetCity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Path", Namespace="http://schemas.datacontract.org/2004/07/TrainsService")]
    [System.SerializableAttribute()]
    public partial class Path : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TrainsServiceReference.ITrainsService")]
    public interface ITrainsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrainsService/GetPaths", ReplyAction="http://tempuri.org/ITrainsService/GetPathsResponse")]
        TrainsClient.TrainsServiceReference.Path[] GetPaths(TrainsClient.TrainsServiceReference.PathsQuery pathsQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrainsService/GetPaths", ReplyAction="http://tempuri.org/ITrainsService/GetPathsResponse")]
        System.Threading.Tasks.Task<TrainsClient.TrainsServiceReference.Path[]> GetPathsAsync(TrainsClient.TrainsServiceReference.PathsQuery pathsQuery);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrainsServiceChannel : TrainsClient.TrainsServiceReference.ITrainsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrainsServiceClient : System.ServiceModel.ClientBase<TrainsClient.TrainsServiceReference.ITrainsService>, TrainsClient.TrainsServiceReference.ITrainsService {
        
        public TrainsServiceClient() {
        }
        
        public TrainsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrainsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrainsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrainsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TrainsClient.TrainsServiceReference.Path[] GetPaths(TrainsClient.TrainsServiceReference.PathsQuery pathsQuery) {
            return base.Channel.GetPaths(pathsQuery);
        }
        
        public System.Threading.Tasks.Task<TrainsClient.TrainsServiceReference.Path[]> GetPathsAsync(TrainsClient.TrainsServiceReference.PathsQuery pathsQuery) {
            return base.Channel.GetPathsAsync(pathsQuery);
        }
    }
}
